name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    
    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: configure
      run: mkdir build && cd build && cmake cmake -DCMAKE_BUILD_TYPE=Debug

    - name: build
      run: cmake --build "."

    - name: run test
      run: cd .. & python3 test/polyscope_test.py
