name: Test Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
      
    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: install packages
      run: sudo apt-get install -y xorg-dev libglu1-mesa-dev xpra xserver-xorg-video-dummy freeglut3-dev

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: build
      run: make

    - name: run test
      run: cd .. & python3 test/polyscope_test.py
